package HOTELL;



import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.security.Security;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Address;
import javax.mail.Authenticator;
import javax.mail.BodyPart;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import project.*;
import javax.swing.table.DefaultTableModel;
import project.ConnectionProvider;



public class CustomerCheckOut extends javax.swing.JFrame  {

      
           
            

 
            
    public CustomerCheckOut() {
        initComponents();
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        jTextField7.setEditable(false);
        jTextField8.setEditable(false);
        jTextField9.setEditable(false);
        
    }
    int id=0;
    String Query;
    String roomType;
    String bed;
    String roomNo;
    
    private PdfPCell createCell(String content, BaseColor backgroundColor) {
    PdfPCell cell = new PdfPCell(new Phrase(content));
    cell.setBackgroundColor(backgroundColor);
    cell.setBorder(Rectangle.NO_BORDER);
    cell.setPadding(5);
    return cell;
}
  
            
               

   // System.out.println("Message sent: "+ message.getSid());
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(30, 118));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-logout-50.png"))); // NOI18N
        jLabel1.setText("Customer Check_Out");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 13, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Room ID Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, 20));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 107, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "MobileNumber", "nationality", "Gender", "Email", "ID Proof", "Address", "CheckIN Date", "Room Number", "Bed", "Room Type", "Price Per Day"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 357, 1230, 230));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Customer Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 260, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Check IN Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 250, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Check Out Date(Today)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, -1, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 250, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Customer Mobile Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 120, -1, -1));

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 160, 280, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Booking price for today");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 260, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Number of Days Stay");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 250, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Total amount to be collected from the customer");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 200, -1, -1));

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 240, 280, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Email");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, -1, -1));

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 250, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-approval.gif"))); // NOI18N
        jButton3.setText("Check Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 270, -1, 70));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Clear window");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 140, 70));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close.gif"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1221, 0, 49, 49));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customer CHICK_OUT_.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ResultSet rs=Select.getData("select * from customer where checkOut is NULL");
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        try
        {
         while(rs.next())   
         {
             model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12),rs.getString(13)});
             
         }
            rs.close();
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_formComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String roomNo=jTextField1.getText();
        try
        {
         ResultSet rs=Select.getData("select * from customer where roomNo='"+roomNo+"' and checkout is NULL");
         if(rs.next())
         {
          jTextField1.setEditable(false);
          id=rs.getInt(1);
          jTextField2.setText(rs.getString(2));
          jTextField3.setText(rs.getString(9));
          jTextField5.setText(rs.getString(3));
          jTextField6.setText(rs.getString(13));
          
          
            SimpleDateFormat  myFormat = new SimpleDateFormat("yyyy/MM/dd");
             Calendar cal=Calendar.getInstance();
             jTextField4.setText(myFormat.format(cal.getTime()));
             String dateBeforeString=rs.getString(9);
             java.util.Date dateBefore=myFormat.parse(dateBeforeString);
             String dateAfterString=myFormat.format(cal.getTime());
             java.util.Date dateAfter=myFormat.parse(dateAfterString);
             long difference=dateAfter.getTime() - dateBefore.getTime();
             int noOfDaystay=(int) (difference/(1000*60*60*24));
            if(noOfDaystay==0) 
             noOfDaystay=1;
            jTextField7.setText(String.valueOf(noOfDaystay));
            float price=Float.parseFloat(jTextField6.getText());
            jTextField8.setText(String.valueOf(noOfDaystay*price));
            jTextField9.setText(rs.getString(6));
            roomType=rs.getString(12);
            bed=rs.getString(11);
            
         }
            else
             JOptionPane.showMessageDialog(null, "Room Number is not Booked or Room  Number Does not Exist");
           
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
         new CustomerCheckOut().setVisible(true);
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String name=jTextField2.getText();
        String mobileNumber=jTextField5.getText();
        String email=jTextField9.getText();
        
        String checkOut=jTextField4.getText();
        String numberOfDaysStay=jTextField7.getText();
        String totalAmount=jTextField8.getText();
        roomNo=jTextField1.getText();
        
        Query=("update customer set numberOfDaysStay='"+numberOfDaysStay+"',totalAmount='"+totalAmount+"',checkOut='"+checkOut+"' where id='"+id+"'");
        InsertUpdateDelete.setData(Query, "");
        Query="update room set Status='Not Booked' where roomNo='"+roomNo+"'";
        InsertUpdateDelete.setData(Query, "");
        String path="D:\\";
        com.itextpdf.text.Document doc=new com.itextpdf.text.Document();
        //com.itextpdf.text.Document doc= new com.itextpdf.text.Document();
       
        if (name == null || name.isEmpty() || mobileNumber == null || mobileNumber.isEmpty() || email == null || email.isEmpty()) {
    // في حالة عدم وجود أي من البيانات الأساسية
    JOptionPane.showMessageDialog(null, "No client data to create PDF", "ERROR", JOptionPane.ERROR_MESSAGE);
} else {

        
        /*try
        {
          PdfWriter.getInstance(doc, new FileOutputStream(path+""+id+".pdf"));
            doc.open();
           Paragraph  Paragraph1= new Paragraph(" MOHAMED RAMADAN TECH Hotel Management System\n");
           doc.add(Paragraph1);
           Paragraph  Paragraph2= new Paragraph("****************************************************************************************************************");
           doc.add(Paragraph2);
           Paragraph  Paragraph3= new Paragraph("\tBill ID: "+id+"\nCustomer Details:\nName: "+name+"\nMobile Number: "+mobileNumber+"\nEmail: "+email+"\n");
           doc.add(Paragraph3);
           doc.add(Paragraph2);
           Paragraph  Paragraph4= new Paragraph("\tRoom Details:\nNumber: "+jTextField1.getText()+"\nType: "+roomType+"\nbed: "+bed+"\nPrice Per Day: "+jTextField6.getText()+"");
           doc.add(Paragraph4);
           doc.add(Paragraph2);
           
           PdfPTable tb1=new PdfPTable(4);
           tb1.addCell("Check IN Date: "+jTextField3.getText());
           tb1.addCell("Check Out Date: "+checkOut);
           tb1.addCell("No of Days Stay: "+numberOfDaysStay);
           tb1.addCell("Total Amount paid: "+totalAmount);
           doc.add(tb1);
           doc.add(Paragraph2);
           Paragraph  Paragraph5= new Paragraph("Thank you, Please Visit Again.");
           doc.add(Paragraph5);
           
           
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }finally{
          doc.close();  
        }*/
  
 
       try {
    // إعداد المستند وكتابة الملف
    PdfWriter.getInstance(doc, new FileOutputStream(path + "" + id + ".pdf"));
    doc.open();
            
    // إضافة الشعار (في مكان مناسب)
    try {
        Image logo = Image.getInstance("C:\\Users\\HP\\Documents\\NetBeansProjects\\Hotel_mohamed_ramadan\\src\\images\\Hotel_Home_mohamed_ramadan.jpg"); // ضع مسار الشعار هنا
        logo.scaleToFit(150, 150); // تعديل الحجم إذا لزم الأمر
        logo.setAlignment(Element.ALIGN_CENTER);
        doc.add(logo);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }

    // العنوان الرئيسي مع تنسيق اللون
    Font titleFont = new Font(Font.FontFamily.TIMES_ROMAN, 30, Font.BOLD, BaseColor.BLUE); // لون أزرق
    Paragraph title = new Paragraph("MOHAMED RAMADAN Hotel Flory\n", titleFont);
    title.setAlignment(Element.ALIGN_CENTER);
    doc.add(title);

    // الخط الفاصل
    Paragraph separator = new Paragraph("****************************************************************************************************************");
separator.setAlignment(Element.ALIGN_CENTER);
doc.add(separator);

    // تفاصيل العميل
    Font customerFont = new Font(Font.FontFamily.HELVETICA, 12, Font.NORMAL, BaseColor.BLACK);
    Paragraph customerDetails = new Paragraph("\tInvoice ID: " + id + "\nCustomer booking details:\nName: " + name + "\nMobile Number: " + mobileNumber + "\nEmail: " + email + "\n", customerFont);
    doc.add(customerDetails);

    // الخط الفاصل
    doc.add(separator);

    // تفاصيل الغرفة بتنسيق مختلف
    Font roomFont = new Font(Font.FontFamily.HELVETICA, 12, Font.NORMAL, BaseColor.BLACK);
    Paragraph roomDetails = new Paragraph("\tRoom Details:\nNumber: " + jTextField1.getText() + "\nBed: " + bed + "\nType: " + roomType + "\nPrice Per Day: " + jTextField6.getText(), roomFont);
    doc.add(roomDetails);
                                                                                                
    // الخط الفاصل
    doc.add(separator);

    // إضافة جدول
    PdfPTable tb1 = new PdfPTable(4);
    tb1.addCell(createCell("Check_IN Date: " + jTextField3.getText(), BaseColor.LIGHT_GRAY));
    tb1.addCell(createCell("Check_Out Date: " + checkOut, BaseColor.LIGHT_GRAY));
    tb1.addCell(createCell("Number of days of stay for the customer: " + numberOfDaysStay, BaseColor.LIGHT_GRAY));
    tb1.addCell(createCell("Total amount collected: " + totalAmount, BaseColor.LIGHT_GRAY));
    doc.add(tb1);

    // الخط الفاصل
    doc.add(separator);

    // رسالة الشكر
    Font thankYouFont = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD, BaseColor.BLUE); // لون أخضر
    Paragraph thankYouMessage = new Paragraph("Thank you, please visit the hotel again.", thankYouFont);
    thankYouMessage.setAlignment(Element.ALIGN_CENTER);
    doc.add(thankYouMessage);

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
} finally {
    // التأكد من أنه يتم غلق المستند فقط بعد إضافة المحتوى
    if (doc.isOpen()) {
        doc.close();
    }
}

        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        /*Properties pro = new Properties();
  pro.put("mail.smtp.host", "smtp.gmail.com");
  pro.put("mail.smtp.port","587");
  pro.put("mail.smtp.ssl.enable", "true");
  pro.put("mail.smtp.starttls.enable", "true");
  pro.put("mail.smtp.starttls.required", "true");

  pro.put("mail.smtp.ssl.protocols", "TLSv1.3");
  pro.put("mail.smtp.auth", "true");
  pro.put("mail.smtp.user", "mohamedsene097@gmail.com"); 
  pro.put("mail.smtp.password", "spby qbjg ekuk xyqa");*/
//pro.put("mail.transport.protocol", "smtp");

Properties pro = new Properties();
pro.put("mail.smtp.host", "smtp.gmail.com");
pro.put("mail.smtp.port", "587");
pro.put("mail.smtp.auth", "true");
pro.put("mail.smtp.starttls.enable", "true");  
pro.put("mail.smtp.ssl.trust", "smtp.gmail.com"); 








String username = "mohamedsene097@gmail.com";
String password = "otwr uudt reip bzgi";
Session session = Session.getInstance(pro, new Authenticator() {
    protected PasswordAuthentication getPasswordAuthentication() {
        return new PasswordAuthentication(username, password);
    }
});

Message message = new MimeMessage(session);
try {
    message.setSubject("هذه هي فاتورتك من MOHAMED RAMADAN TECH.");
    message.setRecipient(Message.RecipientType.TO, new InternetAddress(email)); // استخدام البريد الإلكتروني من jTextField9
    message.setText("Please find attached your invoice.");

    MimeBodyPart messageBodyPart = new MimeBodyPart();
        messageBodyPart.setText("Please find attached your invoice.");
    MimeBodyPart attachmentPart = new MimeBodyPart();
    attachmentPart.attachFile(new File(path + id + ".pdf"));

    Multipart multipart = new MimeMultipart();
    multipart.addBodyPart(messageBodyPart);
    multipart.addBodyPart(attachmentPart);
    message.setContent(multipart);

    Transport.send(message);
    JOptionPane.showMessageDialog(null, "Email sent successfully!");

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
}

       
        
        //............................................
         int a=JOptionPane.showConfirmDialog(null, "Do you want to Print Bill","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            try
            {
               if((new File("D:\\"+id+".pdf")).exists()) 
               {
                 Process p =Runtime
                         .getRuntime()
                         .exec("rundll32 url.dll,FileProtocolHandler D:\\"+id+".pdf");
                 
        try {
           
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "خطأ في إرسال رسالة واتساب: " + e.getMessage());
        }
               }  
               else
                    System.out.println("File is not Exists");
               
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
      
        setVisible(false);
        new CustomerCheckOut().setVisible(true);

       }

    
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCheckOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
