/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HOTELL;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.FlatPropertiesLaf;
import com.formdev.flatlaf.icons.FlatMenuItemArrowIcon;
import com.formdev.flatlaf.icons.FlatWindowMaximizeIcon;
import com.formdev.flatlaf.intellijthemes.FlatMaterialDesignDarkIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTArcDarkIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTGitHubDarkIJTheme;
import com.formdev.flatlaf.ui.FlatFormattedTextFieldUI;
import com.jgoodies.forms.builder.PanelBuilder;
import com.jgoodies.forms.layout.FormLayout;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Insets;
import java.util.Properties;
import static javax.mail.Message.RecipientType.CC;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author HP
 */
public class Lodaing extends javax.swing.JFrame {

    /**
     * Creates new form Lodaing
     */
    //private JLabel percentageLabel;
    //private JLabel statusLabel;
    public Lodaing() {
        initComponents();
//      FlatLightLaf.setup();
//        FlatMTArcDarkIJTheme.setup();
//        FlatMTGitHubDarkIJTheme.setup();
//        FlatMaterialDesignDarkIJTheme.setup();
try {
            

    FlatMTGitHubDarkIJTheme.setup(); // اختار واحد فقط
    UIManager.setLookAndFeel(new FlatMTGitHubDarkIJTheme());
    UIManager.put("Component.focusWidth", 2.5); // يلغي الحدود المتحركة
UIManager.put("Button.showMnemonics", false);



} catch (Exception ex) {
    ex.printStackTrace();
}
        try {
             UIManager.put("Label.foreground", java.awt.Color.WHITE);
    UIManager.put("Button.foreground", java.awt.Color.BLACK);
    UIManager.put("RadioButton.foreground", java.awt.Color.BLACK);
    UIManager.put("CheckBox.foreground", java.awt.Color.BLACK);

        } catch (Exception e) {
        }
       
        
        try {
                        

        } catch (Exception e) {
        }
        
        
        runProgress();  // تشغل التحميل عند إنشاء الواجهة

     
       
        

        // حالة التحميل
//        statusLabel = new JLabel("يتم التحميل الآن...", SwingConstants.CENTER);
//        statusLabel.setFont(new Font("Arial", Font.PLAIN, 16));

        // إضافة المكونات
      
//        add(Lodaing, BorderLayout.CENTER);
//        add(percentageLabel, BorderLayout.WEST);
//        add(statusLabel, BorderLayout.SOUTH);
//              

    }
private void runProgress() {
    new Thread(() -> {
        try {
            for (int i = 0; i <= 100; i++) {
                Thread.sleep(60); // الوقت بين كل تحديث

                // ✅ تحديث الـ progress bar و التسمية
                Lodaing.setValue(i);
                percentageLabel.setText(i + "%");
                statusLabel.setText("يتم التحميل الآن...");
                
                if (i==50) {
                    statusLabel.setText("تم تحميل نصف المده...");
                    Thread.sleep(100);
                }
                

                // ✅ عند اكتمال التحميل
                if (i == 100) {
                    statusLabel.setText("تم التحميل بنجاح");
                    Thread.sleep(500); // توقف بسيط قبل فتح الواجهة التالية
                    dispose(); // إغلاق شاشة التحميل
                    openMainWindow(); // فتح الشاشة الرئيسية
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }).start();
}
    
     private void openMainWindow() {
        // هنا تفتح الواجهة الأساسية للمشروع
        new signup().setVisible(true);  // استبدل MainHome بواجهة مشروعك
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Lodaing = new javax.swing.JProgressBar();
        percentageLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LOD.jpg"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LOD.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lodaingg.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome to the hotel Flory");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1490, 60));

        Lodaing.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Lodaing.setForeground(new java.awt.Color(0, 0, 153));
        Lodaing.setToolTipText("يتم التحميل");
        jPanel1.add(Lodaing, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 740, 1440, 45));

        percentageLabel.setBackground(new java.awt.Color(255, 255, 255));
        percentageLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        percentageLabel.setForeground(new java.awt.Color(255, 255, 255));
        percentageLabel.setText("0%");
        jPanel1.add(percentageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 710, 100));

        statusLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(255, 255, 255));
        statusLabel.setText("يتم التحميل الآن...");
        jPanel1.add(statusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(773, 617, 690, 100));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lodaingg.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
    public static void main(String args[]) {
                SwingUtilities.invokeLater(() -> new Lodaing().setVisible(true));

//       
//         Lodaing lodaing = new Lodaing();
//        
//
//      
//         
//         lodaing.setVisible(true);
//        
//        
//        signup signup1 = new signup();
//        try {
//            for (int i = 0; i < 100;  i++) {
//                Thread.sleep(60);
//                
//                lodaing.Lodaing.setValue(i);
//                lodaing.Lodaing.setToolTipText("يتم التحميل الان"+i);

                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                /*
                
                String studentId = jTextField3.getText(); 
    try {
        if (studentId.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a student ID.");
            return;
        }

        String query = "SELECT s.id_stu, s.full_name, s.phone, s.amount_due, s.teacher_name, " +
                        "c.name_course, c.price " +
                        "FROM students2 s " +
                        "JOIN courses2 c ON s.id_stu = c.id_stt " +
                        "WHERE s.id_stu = ?";
        
        try (Connection connection = DriverManager.getConnection(URL, USER, PASSWORD);
             PreparedStatement ps = connection.prepareStatement(query)) {
            
            ps.setString(1, studentId);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                jTextField3.setEditable(false);
                jTextField12.setText(rs.getString("id_stu"));
                
                jTextField2.setText(rs.getString("phone"));
                jTextField11.setText(String.valueOf(rs.getInt("amount_due")));
                jTextField1.setText(rs.getString("full_name"));
                jTextField8.setText(rs.getString("name_courses"));
                jTextField9.setText(rs.getString("price"));
                jTextField10.setText(rs.getString("id_corrss"));

                
                jTextField5.setText(rs.getString("teacher_name"));

                String teacherName = rs.getString("teacher_name");
                jComboBox2.setSelectedItem(teacherName); 

                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0); 

                do {
                    model.addRow(new Object[]{
                        rs.getString("id_stu");
                        rs.getString("full_name");
                        rs.getString("phone");
                        rs.getString("teacher_name");
                

                rs.getString("name_course"),  
                        rs.getFloat("price")          
                    });
                } while (rs.next()); 
            } else {
                JOptionPane.showMessageDialog(null, "No student found with this ID.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error fetching student data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
                
                
                
                
                
                
                
                
                
                
                */
//                
//            }
//        } catch (Exception e) {
//        }
//        
//        lodaing.setVisible(false);
//        signup1.setVisible(true);
//        lodaing.dispose();
//    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Lodaing;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel percentageLabel;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
